//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocal_map.proto
namespace gprotocol
{
    [global::ProtoBuf.ProtoContract(Name=@"MapEnum")]
    public enum MapEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=0)]
      Login = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dating", Value=1001)]
      Dating = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Zhandou", Value=1002)]
      Zhandou = 1002
    }
  
}