//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tnt_deploy_crazy_info.proto
namespace tnt_deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CRAZY_INFO")]
  public partial class CRAZY_INFO : global::ProtoBuf.IExtensible
  {
    public CRAZY_INFO() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _dengji = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dengji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int dengji
    {
      get { return _dengji; }
      set { _dengji = value; }
    }
    private byte[] _bingzhong = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bingzhong", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] bingzhong
    {
      get { return _bingzhong; }
      set { _bingzhong = value; }
    }
    private int _shengming_dengji = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"shengming_dengji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int shengming_dengji
    {
      get { return _shengming_dengji; }
      set { _shengming_dengji = value; }
    }
    private float _shengming_pinzhi = (float)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"shengming_pinzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float shengming_pinzhi
    {
      get { return _shengming_pinzhi; }
      set { _shengming_pinzhi = value; }
    }
    private int _gongjili_dengji = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gongjili_dengji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int gongjili_dengji
    {
      get { return _gongjili_dengji; }
      set { _gongjili_dengji = value; }
    }
    private float _gongjili_pinzhi = (float)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gongjili_pinzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float gongjili_pinzhi
    {
      get { return _gongjili_pinzhi; }
      set { _gongjili_pinzhi = value; }
    }
    private float _speed = (float)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _zhiliao_dengji = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"zhiliao_dengji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int zhiliao_dengji
    {
      get { return _zhiliao_dengji; }
      set { _zhiliao_dengji = value; }
    }
    private float _zhiliao_pinzhi = (float)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"zhiliao_pinzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float zhiliao_pinzhi
    {
      get { return _zhiliao_pinzhi; }
      set { _zhiliao_pinzhi = value; }
    }
    private float _jingzun = (float)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"jingzun", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float jingzun
    {
      get { return _jingzun; }
      set { _jingzun = value; }
    }
    private float _fanwei = (float)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fanwei", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float fanwei
    {
      get { return _fanwei; }
      set { _fanwei = value; }
    }
    private int _shengming_base = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"shengming_base", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int shengming_base
    {
      get { return _shengming_base; }
      set { _shengming_base = value; }
    }
    private int _gongji_base = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"gongji_base", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int gongji_base
    {
      get { return _gongji_base; }
      set { _gongji_base = value; }
    }
    private int _zhiliao_base = (int)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"zhiliao_base", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int zhiliao_base
    {
      get { return _zhiliao_base; }
      set { _zhiliao_base = value; }
    }
    private int _dalei = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"dalei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int dalei
    {
      get { return _dalei; }
      set { _dalei = value; }
    }
    private int _xingji = (int)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"xingji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int xingji
    {
      get { return _xingji; }
      set { _xingji = value; }
    }
    private int _jingyan_shangxian = (int)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"jingyan_shangxian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int jingyan_shangxian
    {
      get { return _jingyan_shangxian; }
      set { _jingyan_shangxian = value; }
    }
    private int _pinzhi = (int)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"pinzhi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int pinzhi
    {
      get { return _pinzhi; }
      set { _pinzhi = value; }
    }
    private int _pinzhi_zhonglei = (int)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"pinzhi_zhonglei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int pinzhi_zhonglei
    {
      get { return _pinzhi_zhonglei; }
      set { _pinzhi_zhonglei = value; }
    }
    private float _jiacheng_zuidi = (float)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"jiacheng_zuidi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float jiacheng_zuidi
    {
      get { return _jiacheng_zuidi; }
      set { _jiacheng_zuidi = value; }
    }
    private float _jiacheng_zuigao = (float)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"jiacheng_zuigao", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float jiacheng_zuigao
    {
      get { return _jiacheng_zuigao; }
      set { _jiacheng_zuigao = value; }
    }
    private float _jiachengbi = (float)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"jiachengbi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float jiachengbi
    {
      get { return _jiachengbi; }
      set { _jiachengbi = value; }
    }
    private int _s_dengji = (int)0;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"s_dengji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int s_dengji
    {
      get { return _s_dengji; }
      set { _s_dengji = value; }
    }
    private int _jingyan = (int)0;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"jingyan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int jingyan
    {
      get { return _jingyan; }
      set { _jingyan = value; }
    }
    private int _jingyan_xiaohao = (int)0;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"jingyan_xiaohao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int jingyan_xiaohao
    {
      get { return _jingyan_xiaohao; }
      set { _jingyan_xiaohao = value; }
    }
    private int _jinbi_xiaohao = (int)0;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"jinbi_xiaohao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int jinbi_xiaohao
    {
      get { return _jinbi_xiaohao; }
      set { _jinbi_xiaohao = value; }
    }
    private int _jinbi_chushou = (int)0;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"jinbi_chushou", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int jinbi_chushou
    {
      get { return _jinbi_chushou; }
      set { _jinbi_chushou = value; }
    }
    private string _yulantu = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"yulantu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string yulantu
    {
      get { return _yulantu; }
      set { _yulantu = value; }
    }
    private int _shangxian = (int)0;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"shangxian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int shangxian
    {
      get { return _shangxian; }
      set { _shangxian = value; }
    }
    private float _a_fanweishanghai = (float)0;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"a_fanweishanghai", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_fanweishanghai
    {
      get { return _a_fanweishanghai; }
      set { _a_fanweishanghai = value; }
    }
    private float _a_gongjifudong = (float)0;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"a_gongjifudong", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_gongjifudong
    {
      get { return _a_gongjifudong; }
      set { _a_gongjifudong = value; }
    }
    private float _a_gongjijiange = (float)0;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"a_gongjijiange", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_gongjijiange
    {
      get { return _a_gongjijiange; }
      set { _a_gongjijiange = value; }
    }
    private float _a_gongjijiange_huifuzhi = (float)0;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"a_gongjijiange_huifuzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_gongjijiange_huifuzhi
    {
      get { return _a_gongjijiange_huifuzhi; }
      set { _a_gongjijiange_huifuzhi = value; }
    }
    private float _u_shengmingzhi = (float)0;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"u_shengmingzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_shengmingzhi
    {
      get { return _u_shengmingzhi; }
      set { _u_shengmingzhi = value; }
    }
    private float _u_shengmingzhi_max = (float)0;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"u_shengmingzhi_max", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_shengmingzhi_max
    {
      get { return _u_shengmingzhi_max; }
      set { _u_shengmingzhi_max = value; }
    }
    private float _a_gongjili = (float)0;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"a_gongjili", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_gongjili
    {
      get { return _a_gongjili; }
      set { _a_gongjili = value; }
    }
    private float _a_gongjili_huifuzhi = (float)0;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"a_gongjili_huifuzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_gongjili_huifuzhi
    {
      get { return _a_gongjili_huifuzhi; }
      set { _a_gongjili_huifuzhi = value; }
    }
    private float _a_gongjiqianyao = (float)0;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"a_gongjiqianyao", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_gongjiqianyao
    {
      get { return _a_gongjiqianyao; }
      set { _a_gongjiqianyao = value; }
    }
    private float _a_gongjiqianyao_huifuzhi = (float)0;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"a_gongjiqianyao_huifuzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_gongjiqianyao_huifuzhi
    {
      get { return _a_gongjiqianyao_huifuzhi; }
      set { _a_gongjiqianyao_huifuzhi = value; }
    }
    private int _a_guanchuangesu = (int)0;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"a_guanchuangesu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int a_guanchuangesu
    {
      get { return _a_guanchuangesu; }
      set { _a_guanchuangesu = value; }
    }
    private float _a_jiansu = (float)0;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"a_jiansu", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_jiansu
    {
      get { return _a_jiansu; }
      set { _a_jiansu = value; }
    }
    private float _a_jiansu_shijian = (float)0;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"a_jiansu_shijian", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_jiansu_shijian
    {
      get { return _a_jiansu_shijian; }
      set { _a_jiansu_shijian = value; }
    }
    private float _a_jingzhundu = (float)0;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"a_jingzhundu", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_jingzhundu
    {
      get { return _a_jingzhundu; }
      set { _a_jingzhundu = value; }
    }
    private float _a_jitui = (float)0;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"a_jitui", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_jitui
    {
      get { return _a_jitui; }
      set { _a_jitui = value; }
    }
    private int _a_jitui_zhiliang = (int)0;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"a_jitui_zhiliang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int a_jitui_zhiliang
    {
      get { return _a_jitui_zhiliang; }
      set { _a_jitui_zhiliang = value; }
    }
    private int _a_leixing = (int)0;
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"a_leixing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int a_leixing
    {
      get { return _a_leixing; }
      set { _a_leixing = value; }
    }
    private float _a_shecheng = (float)0;
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"a_shecheng", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_shecheng
    {
      get { return _a_shecheng; }
      set { _a_shecheng = value; }
    }
    private string _a_shoujipandingmoxing = "";
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"a_shoujipandingmoxing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string a_shoujipandingmoxing
    {
      get { return _a_shoujipandingmoxing; }
      set { _a_shoujipandingmoxing = value; }
    }
    private float _a_xuanyun = (float)0;
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"a_xuanyun", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_xuanyun
    {
      get { return _a_xuanyun; }
      set { _a_xuanyun = value; }
    }
    private float _a_zhonglipaoshe = (float)0;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"a_zhonglipaoshe", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_zhonglipaoshe
    {
      get { return _a_zhonglipaoshe; }
      set { _a_zhonglipaoshe = value; }
    }
    private float _a_zidanhudubilv = (float)0;
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"a_zidanhudubilv", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_zidanhudubilv
    {
      get { return _a_zidanhudubilv; }
      set { _a_zidanhudubilv = value; }
    }
    private string _a_zidanmoxing = "";
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"a_zidanmoxing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string a_zidanmoxing
    {
      get { return _a_zidanmoxing; }
      set { _a_zidanmoxing = value; }
    }
    private float _a_zidansudu = (float)0;
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"a_zidansudu", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_zidansudu
    {
      get { return _a_zidansudu; }
      set { _a_zidansudu = value; }
    }
    private bool _a_zidao = default(bool);
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"a_zidao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool a_zidao
    {
      get { return _a_zidao; }
      set { _a_zidao = value; }
    }
    private float _a_zilaoshuzi = (float)0;
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"a_zilaoshuzi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a_zilaoshuzi
    {
      get { return _a_zilaoshuzi; }
      set { _a_zilaoshuzi = value; }
    }
    private bool _a_ziliao = default(bool);
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"a_ziliao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool a_ziliao
    {
      get { return _a_ziliao; }
      set { _a_ziliao = value; }
    }
    private string _c_jineng = "";
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"c_jineng", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string c_jineng
    {
      get { return _c_jineng; }
      set { _c_jineng = value; }
    }
    private string _f_zidan_baozha = "";
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"f_zidan_baozha", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string f_zidan_baozha
    {
      get { return _f_zidan_baozha; }
      set { _f_zidan_baozha = value; }
    }
    private string _f_zidan_fashe = "";
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"f_zidan_fashe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string f_zidan_fashe
    {
      get { return _f_zidan_fashe; }
      set { _f_zidan_fashe = value; }
    }
    private string _n_mingzi_usen = "";
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"n_mingzi_usen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string n_mingzi_usen
    {
      get { return _n_mingzi_usen; }
      set { _n_mingzi_usen = value; }
    }
    private string _n_mingzi_zhcn = "";
    [global::ProtoBuf.ProtoMember(62, IsRequired = false, Name=@"n_mingzi_zhcn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string n_mingzi_zhcn
    {
      get { return _n_mingzi_zhcn; }
      set { _n_mingzi_zhcn = value; }
    }
    private string _s_shengyin = "";
    [global::ProtoBuf.ProtoMember(63, IsRequired = false, Name=@"s_shengyin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s_shengyin
    {
      get { return _s_shengyin; }
      set { _s_shengyin = value; }
    }
    private string _s_zidan_yinxiao = "";
    [global::ProtoBuf.ProtoMember(64, IsRequired = false, Name=@"s_zidan_yinxiao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s_zidan_yinxiao
    {
      get { return _s_zidan_yinxiao; }
      set { _s_zidan_yinxiao = value; }
    }
    private float _u_baohutao_daxiao = (float)0;
    [global::ProtoBuf.ProtoMember(65, IsRequired = false, Name=@"u_baohutao_daxiao", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_baohutao_daxiao
    {
      get { return _u_baohutao_daxiao; }
      set { _u_baohutao_daxiao = value; }
    }
    private float _u_baohutao_shengming = (float)0;
    [global::ProtoBuf.ProtoMember(66, IsRequired = false, Name=@"u_baohutao_shengming", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_baohutao_shengming
    {
      get { return _u_baohutao_shengming; }
      set { _u_baohutao_shengming = value; }
    }
    private int _u_dengji = (int)0;
    [global::ProtoBuf.ProtoMember(67, IsRequired = false, Name=@"u_dengji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int u_dengji
    {
      get { return _u_dengji; }
      set { _u_dengji = value; }
    }
    private float _u_donghuasulv = (float)0;
    [global::ProtoBuf.ProtoMember(68, IsRequired = false, Name=@"u_donghuasulv", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_donghuasulv
    {
      get { return _u_donghuasulv; }
      set { _u_donghuasulv = value; }
    }
    private float _u_donghuasulv_huifuzhi = (float)0;
    [global::ProtoBuf.ProtoMember(69, IsRequired = false, Name=@"u_donghuasulv_huifuzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_donghuasulv_huifuzhi
    {
      get { return _u_donghuasulv_huifuzhi; }
      set { _u_donghuasulv_huifuzhi = value; }
    }
    private float _u_jiangli = (float)0;
    [global::ProtoBuf.ProtoMember(70, IsRequired = false, Name=@"u_jiangli", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_jiangli
    {
      get { return _u_jiangli; }
      set { _u_jiangli = value; }
    }
    private float _u_jiaosetiji_h = (float)0;
    [global::ProtoBuf.ProtoMember(71, IsRequired = false, Name=@"u_jiaosetiji_h", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_jiaosetiji_h
    {
      get { return _u_jiaosetiji_h; }
      set { _u_jiaosetiji_h = value; }
    }
    private float _u_jiaosetiji_r = (float)0;
    [global::ProtoBuf.ProtoMember(72, IsRequired = false, Name=@"u_jiaosetiji_r", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_jiaosetiji_r
    {
      get { return _u_jiaosetiji_r; }
      set { _u_jiaosetiji_r = value; }
    }
    private float _u_jiaosetiji_y = (float)0;
    [global::ProtoBuf.ProtoMember(73, IsRequired = false, Name=@"u_jiaosetiji_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_jiaosetiji_y
    {
      get { return _u_jiaosetiji_y; }
      set { _u_jiaosetiji_y = value; }
    }
    private bool _u_jihuo = default(bool);
    [global::ProtoBuf.ProtoMember(74, IsRequired = false, Name=@"u_jihuo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool u_jihuo
    {
      get { return _u_jihuo; }
      set { _u_jihuo = value; }
    }
    private string _u_moxing = "";
    [global::ProtoBuf.ProtoMember(75, IsRequired = false, Name=@"u_moxing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string u_moxing
    {
      get { return _u_moxing; }
      set { _u_moxing = value; }
    }
    private long _u_wanjia = (long)0;
    [global::ProtoBuf.ProtoMember(76, IsRequired = false, Name=@"u_wanjia", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long u_wanjia
    {
      get { return _u_wanjia; }
      set { _u_wanjia = value; }
    }
    private float _u_yidongsudu = (float)0;
    [global::ProtoBuf.ProtoMember(77, IsRequired = false, Name=@"u_yidongsudu", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_yidongsudu
    {
      get { return _u_yidongsudu; }
      set { _u_yidongsudu = value; }
    }
    private float _u_yidongsudu_huifuzhi = (float)0;
    [global::ProtoBuf.ProtoMember(78, IsRequired = false, Name=@"u_yidongsudu_huifuzhi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float u_yidongsudu_huifuzhi
    {
      get { return _u_yidongsudu_huifuzhi; }
      set { _u_yidongsudu_huifuzhi = value; }
    }
    private int _configId = (int)0;
    [global::ProtoBuf.ProtoMember(79, IsRequired = false, Name=@"configId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int configId
    {
      get { return _configId; }
      set { _configId = value; }
    }
    private int _subSystemId = (int)0;
    [global::ProtoBuf.ProtoMember(80, IsRequired = false, Name=@"subSystemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int subSystemId
    {
      get { return _subSystemId; }
      set { _subSystemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CRAZY_INFO_ARRAY")]
  public partial class CRAZY_INFO_ARRAY : global::ProtoBuf.IExtensible
  {
    public CRAZY_INFO_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<tnt_deploy.CRAZY_INFO> _items = new global::System.Collections.Generic.List<tnt_deploy.CRAZY_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tnt_deploy.CRAZY_INFO> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}